# Generated by Django 3.2 on 2022-01-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_reservation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='number_in_stock',
        ),
    ]
