# Generated by Django 3.2 on 2022-01-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_reservation_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('cancel_reservation', 'Can cancel reservation')]},
        ),
    ]
