# Generated by Django 3.2.9 on 2021-12-11 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0006_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(default=datetime.date.today)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bicycles.bicycle')),
            ],
        ),
    ]
