# Generated by Django 2.1 on 2021-10-19 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
