# Generated by Django 3.2.8 on 2021-11-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_bicycle_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='image_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
