# Generated by Django 3.2.8 on 2021-11-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_bicycle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
