# Generated by Django 3.2.9 on 2021-12-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0005_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
